services:
  nginx:
    build: .
    image: mynginx
    container_name: mynginx-container
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - mynginx:/usr/share/nginx/html
    expose:
      - "8080"
    restart: unless-stopped

volumes:
  mynginx:
    external: true
