services:
  djangogirls:
    build: .
    container_name: djangogirls-container
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    ports:
      - "8000:8000"
    command: python3 manage.py runserver 0.0.0.0:8000
    restart: unless-stopped

  migrate:
    build: .
    container_name: djangogirls-migrate
    depends_on:
      db:
        condition: service_healthy
    command: sh init.sh

  db:
    image: postgres:16-alpine
    container_name: djangogirls-db
    environment:
      POSTGRES_DB: django
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django
    volumes:
      - postgresql:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "django"]
      interval: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgresql:
    external: true
